[package]
name = "discord_guild_spammer"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.20.2"
rand = "0.8.5"
serenity = { version = "0.12.4", features = ["full"] }
tokio = { version = "1.42.0", features = ["full"] }
